### ISSUE TITLE
Page id: dbd 02 - is notice right - do want hint at bottom to be a help with green text and '?' or a note under field?

### ISSUE THREAD

**Issue by CaroRob** [CaroRob/docassemble-DeadBrokeDads#59]
At the bottom of this screen when we ask if arrears is correct, we have a Note that tells people that the arrears DOR has calculated may be wrong from obligors calculations because DOR's calcs include interest reported to federal gov. 

Do we want the hint at the bottom to be a help with green text and '?' or a note under field?

**Comment by bsiegel7** [comment]
I think green text and ?

From: Caroline Robinson ***@***.***>
Sent: Monday, March 15, 2021 4:40 PM
To: CaroRob/docassemble-DeadBrokeDads ***@***.***>
Cc: Barbara Siegel ***@***.***>; Assign ***@***.***>
Subject: [CaroRob/docassemble-DeadBrokeDads] Page id: dbd 02 - is notice right - do want hint at bottom to be a help with green text and '?' or a note under field? (#59)


At the bottom of this screen when we ask if arrears is correct, we have a Note that tells people that the arrears DOR has calculated may be wrong from obligors calculations because DOR's calcs include interest reported to federal gov.

Do we want the hint at the bottom to be a help with green text and '?' or a note under field?

**Comment by CaroRob** [comment]
Done
